package com.mycompany.trabalho_redes.parte1.view;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.mycompany.trabalho_redes.parte1.controller.Controller;
import com.mycompany.trabalho_redes.parte1.model.Message;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class GUI extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(GUI.class.getName());

    private Controller controller;
    private Thread chat_msgThread;

    /**
     * Creates new form GUI
     *
     * @throws java.lang.InterruptedException
     */
    public GUI() throws InterruptedException {
        initComponents();
        controller = new Controller();
        updateChat();
        LOG.info("GUI iniciada.\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_label = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        atualizar_button = new javax.swing.JButton();
        conversa_textarea = new javax.swing.JScrollPane();
        mensagens_textarea = new javax.swing.JTextArea();
        separador1 = new javax.swing.JSeparator();
        msg_label = new javax.swing.JLabel();
        msg_textfield = new javax.swing.JTextField();
        send_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ip_label = new javax.swing.JLabel();
        port_label = new javax.swing.JLabel();
        port_textfield = new javax.swing.JTextField();
        entrar_button = new javax.swing.JButton();
        ip_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_label.setText("Nome de usuário:");

        atualizar_button.setText("Atualizar");
        atualizar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_buttonActionPerformed(evt);
            }
        });

        mensagens_textarea.setColumns(20);
        mensagens_textarea.setRows(5);
        conversa_textarea.setViewportView(mensagens_textarea);

        msg_label.setText("Mensagem:");

        send_button.setText("Enviar");
        send_button.setEnabled(false);
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });

        ip_label.setText("IP multicast:");

        port_label.setText("PORT:");

        entrar_button.setText("Entrar");
        entrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conversa_textarea)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(send_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ip_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(port_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(port_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(entrar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(username_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar_button))
                .addGap(18, 18, 18)
                .addComponent(conversa_textarea, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msg_label)
                    .addComponent(msg_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_button))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ip_label)
                    .addComponent(port_label)
                    .addComponent(port_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrar_button)
                    .addComponent(ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        Message m = new Message(controller.getTx().getUsername(), this.msg_textfield.getText());
        try {
            controller.send(m);
            LOG.info("Mensagem enviada: " + m.toString()+ "\n");
        } catch (Exception ex) {
            LOG.log(Level.SEVERE, "Erro ao enviar mensagem " + ex+ "\n");
            JOptionPane.showConfirmDialog(this, "Erro ao enviar mensagem:\n" + ex.getMessage());
        }
        this.msg_textfield.setText("");
    }//GEN-LAST:event_send_buttonActionPerformed

    private void atualizar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_buttonActionPerformed
        try {
            this.controller.getTx().setUsername(this.username_textfield.getText());
            verifyInputs();
            LOG.info("Username atualizado para: " + this.controller.getTx().getUsername()+ "\n");
        } catch (IOException ex) {
            LOG.log(Level.SEVERE, "Erro ao atualizar username ", ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_atualizar_buttonActionPerformed

    private void entrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_buttonActionPerformed
        try {
            String ip = this.ip_textfield.getText();
            int port = Integer.parseInt(this.port_textfield.getText());
            String username = this.username_textfield.getText();

            controller.enter(ip, port, username);
            LOG.info("Entrou no grupo: " + ip + ":" + port + " como " + username+ "\n");

            verifyInputs();
        } catch (IOException | NumberFormatException ex) {
            LOG.log(Level.SEVERE, "Erro de conexão (IO/Número)" + ex + "\n");
            JOptionPane.showMessageDialog(this, "Erro ao conectar: " + ex.getMessage());
        } catch (Exception ex) {
            LOG.log(Level.SEVERE, "Erro geral ao tentar conectar " + ex + "\n");
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_entrar_buttonActionPerformed

    private void verifyInputs() throws JsonProcessingException {
        boolean send = this.controller.getNh() != null
                && !this.controller.getTx().getUsername().isBlank()
                && this.controller.getRx() != null;
        this.send_button.setEnabled(send);
    }

    private void updateChat() throws InterruptedException {
        chat_msgThread = new Thread(() -> {
            try {
                controller.getChat_msgs().add("\n");
                while (true) {
                    if (controller.getFila_mensagens().isEmpty()) {
                        Thread.sleep(500);
                    }

                    while (!this.controller.getFila_mensagens().isEmpty()) {
                        Message m = this.controller.getFila_mensagens().poll();
                        
                        this.controller.getChat_msgs().add(
                                m.toString() + "\n"
                        );
                    }

                    this.mensagens_textarea.setText(this.controller.getChat_msgs().toString());
                    Thread.sleep(100);
                }
            } catch (Exception e) {
                LOG.log(Level.SEVERE, "Erro na thread de atualização de chat " + e+ "\n");
                JOptionPane.showConfirmDialog(this, "Erro no chat:\n" + e.getMessage());
            }
        });
        chat_msgThread.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar_button;
    private javax.swing.JScrollPane conversa_textarea;
    private javax.swing.JButton entrar_button;
    private javax.swing.JLabel ip_label;
    private javax.swing.JTextField ip_textfield;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea mensagens_textarea;
    private javax.swing.JLabel msg_label;
    private javax.swing.JTextField msg_textfield;
    private javax.swing.JLabel port_label;
    private javax.swing.JTextField port_textfield;
    private javax.swing.JButton send_button;
    private javax.swing.JSeparator separador1;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
