package com.mycompany.trabalho_redes.parte3.client;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class GUI extends javax.swing.JFrame {
    
    private final Controller c;
    private StringBuilder logger;
    private Thread atualization_thread;
    
    private volatile boolean running = false;

    /**
     * Creates new form GUI
     */
    public GUI(Controller c) {
        this.c = c;
        this.logger = new StringBuilder();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listagem_textarea = new javax.swing.JTextArea();
        listar_button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dispositivo_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        novo_valor_textfield = new javax.swing.JTextField();
        atualizar_button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        listagem_automatica_textfield = new javax.swing.JTextField();
        iniciar_button = new javax.swing.JButton();
        parar_button = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logger_textarea = new javax.swing.JTextArea();
        limpar_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buscar_disp_textfield = new javax.swing.JTextField();
        buscar_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitoramento Filial");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Monitoramento Filial");

        listagem_textarea.setEditable(false);
        listagem_textarea.setColumns(20);
        listagem_textarea.setRows(5);
        jScrollPane1.setViewportView(listagem_textarea);

        listar_button.setText("Listar Dispositivos");
        listar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Alterar Dispositivo (Apenas atuadores)");

        jLabel3.setText("Dispositivo: ");

        jLabel4.setText("Novo Valor");

        atualizar_button.setText("Atualizar");
        atualizar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Listagem Automática (Segundos):");

        iniciar_button.setText("Iniciar");
        iniciar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_buttonActionPerformed(evt);
            }
        });

        parar_button.setText("Parar");
        parar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parar_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setText("LOGGER");

        logger_textarea.setEditable(false);
        logger_textarea.setColumns(20);
        logger_textarea.setRows(5);
        jScrollPane2.setViewportView(logger_textarea);

        limpar_button.setText("Limpar registros");
        limpar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_buttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setText("Buscar Dispositivo:");

        buscar_button.setText("Buscar");
        buscar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atualizar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dispositivo_textfield))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(novo_valor_textfield))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iniciar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listagem_automatica_textfield)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(parar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(limpar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(0, 421, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar_disp_textfield)
                        .addGap(18, 18, 18)
                        .addComponent(buscar_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(buscar_disp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_button))
                .addGap(18, 18, 18)
                .addComponent(listar_button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dispositivo_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(novo_valor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(atualizar_button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(listagem_automatica_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar_button)
                    .addComponent(parar_button))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpar_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_buttonActionPerformed
        try {
            String place = this.buscar_disp_textfield.getText();
            this.get(place);

        } catch (IOException e) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, String.format("Erro na Busca: ", e));
        }
    }//GEN-LAST:event_buscar_buttonActionPerformed

    private void listar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_buttonActionPerformed
        try {
            Map<String, Object> list_resp = this.c.list();
            StringBuilder ans = new StringBuilder();

            ans.append("cmd: ");
            ans.append((String) list_resp.get("cmd")).append("\n");

            ans.append("place: ");
            ans.append(((ArrayList<String>) list_resp.get("place")).toString());

            this.listagem_textarea.setText(ans.toString());
            this.logger.append("Listagem \n");
            this.logger_textarea.setText(logger.toString());

        } catch (IOException e) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, String.format("Erro na Listagem: ", e));
        }
    }//GEN-LAST:event_listar_buttonActionPerformed

    private void atualizar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_buttonActionPerformed
        try {
            String locate = this.dispositivo_textfield.getText();
            String value = this.novo_valor_textfield.getText();

            if (locate.isBlank() || value.isBlank()) {
                throw new Exception("Campos invalidos para atualização");
            }

            Map<String, Object> get_resp = this.c.set(locate, value);
            StringBuilder ans = new StringBuilder();

            ans.append("cmd: ");
            ans.append((String) get_resp.get("cmd")).append("\n");

            ans.append("locate: ");
            ans.append((String) get_resp.get("locate")).append("\n");

            ans.append("value: ");
            ans.append((String) get_resp.get("value")).append("\n");

            this.listagem_textarea.setText(ans.toString());
            this.logger.append("Atualização de dispositivo: ").append(locate).append("\n");
            this.logger_textarea.setText(logger.toString());

        } catch (Exception e) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, String.format("Erro na atualização: ", e));
        }
    }//GEN-LAST:event_atualizar_buttonActionPerformed

    private void iniciar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_buttonActionPerformed
        final int seconds = Integer.parseInt(this.listagem_automatica_textfield.getText()) * 1000;
        this.running = true;
        
        this.atualization_thread = new Thread(() -> {
            try {
                while (running) {
                    this.get("all");
                    Thread.sleep(seconds);
                }
            } catch (InterruptedException | IOException e) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(this, String.format("Erro na listagem automática: ", e));
            }
        }
        );
        atualization_thread.start();
    }//GEN-LAST:event_iniciar_buttonActionPerformed

    private void limpar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_buttonActionPerformed
        this.logger_textarea.setText("");
        this.logger = new StringBuilder("");
    }//GEN-LAST:event_limpar_buttonActionPerformed

    private void parar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parar_buttonActionPerformed
        this.running = false;
        this.logger.append("Busca automática encerrada\n");
        this.logger_textarea.setText(logger.toString());
    }//GEN-LAST:event_parar_buttonActionPerformed

    private void get(String place) throws IOException {
        Map<String, Object> get_resp = this.c.get(place);
        StringBuilder ans = new StringBuilder();

        ans.append("cmd: ");
        ans.append((String) get_resp.get("cmd")).append("\n");

        ans.append("place: ");
        ans.append(get_resp.get("place").toString()).append("\n");

        ans.append("value: ");
        ans.append(get_resp.get("value").toString());

        this.listagem_textarea.setText(ans.toString());
        this.logger.append("Requisicao de busca para o place: ").append("all\n");
        this.logger_textarea.setText(logger.toString());
    }

    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String ip = JOptionPane.showInputDialog("Insira o ip do servidor: ", "###.###.###.###");
        int port = Integer.parseInt(JOptionPane.showInputDialog("Insira a port do servidor: ", "0-65535"));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI(new Controller(new UDPClient(ip, port))).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar_button;
    private javax.swing.JButton buscar_button;
    private javax.swing.JTextField buscar_disp_textfield;
    private javax.swing.JTextField dispositivo_textfield;
    private javax.swing.JButton iniciar_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton limpar_button;
    private javax.swing.JTextField listagem_automatica_textfield;
    private javax.swing.JTextArea listagem_textarea;
    private javax.swing.JButton listar_button;
    private javax.swing.JTextArea logger_textarea;
    private javax.swing.JTextField novo_valor_textfield;
    private javax.swing.JButton parar_button;
    // End of variables declaration//GEN-END:variables
}
